import type { ReachabilityTarget } from "@/lib/reachability-targets";

export const WHITELIST_SOURCE_NEWS: { title: string; href: string }[] = [
  {
    title:
      "Важные интернет-сервисы остаются доступными во время ограничений",
    href: "https://digital.gov.ru/news/vazhnye-internet-servisy-ostayutsya-dostupnymi-vo-vremya-ogranichenij",
  },
  {
    title:
      "Список доступных во время ограничений работы мобильного интернета сайтов дополнен (2)",
    href: "https://digital.gov.ru/news/spisok-dostupnyh-vo-vremya-ogranichenij-raboty-mobilnogo-interneta-sajtov-dopolnen-2",
  },
  {
    title: "Белый список доступных при ограничениях интернета сайтов вновь расширен",
    href: "https://digital.gov.ru/news/belyj-spisok-dostupnyh-pri-ogranicheniyah-interneta-sajtov-vnov-rasshiren",
  },
];

export const WHITE_LIST_REACHABILITY_TARGETS: ReachabilityTarget[] = [
  {
    id: "wl-digital",
    label: "Минцифры (digital.gov.ru)",
    region: "Белый список",
    host: "digital.gov.ru",
    url: "https://digital.gov.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-gosuslugi",
    label: "Госуслуги",
    region: "Белый список",
    host: "gosuslugi.ru",
    url: "https://www.gosuslugi.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-government",
    label: "Правительство РФ",
    region: "Белый список",
    host: "government.ru",
    url: "https://www.government.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-kremlin",
    label: "Кремль",
    region: "Белый список",
    host: "kremlin.ru",
    url: "https://www.kremlin.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-cbr",
    label: "Банк России",
    region: "Белый список",
    host: "cbr.ru",
    url: "https://www.cbr.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-mvd",
    label: "МВД России",
    region: "Белый список",
    host: "mvd.gov.ru",
    url: "https://mvd.gov.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-ria",
    label: "РИА Новости",
    region: "Белый список",
    host: "ria.ru",
    url: "https://ria.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-tass",
    label: "ТАСС",
    region: "Белый список",
    host: "tass.ru",
    url: "https://tass.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-rbc",
    label: "РБК",
    region: "Белый список",
    host: "rbc.ru",
    url: "https://www.rbc.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-ozon",
    label: "Ozon",
    region: "Белый список",
    host: "ozon.ru",
    url: "https://www.ozon.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-wb",
    label: "Wildberries",
    region: "Белый список",
    host: "wildberries.ru",
    url: "https://www.wildberries.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-avito",
    label: "Avito",
    region: "Белый список",
    host: "avito.ru",
    url: "https://www.avito.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-rutube",
    label: "RuTube",
    region: "Белый список",
    host: "rutube.ru",
    url: "https://rutube.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-yandex",
    label: "Яндекс",
    region: "Белый список",
    host: "yandex.ru",
    url: "https://yandex.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-mts",
    label: "МТС",
    region: "Белый список",
    host: "mts.ru",
    url: "https://mts.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-tbank",
    label: "Т-Банк",
    region: "Белый список",
    host: "tbank.ru",
    url: "https://www.tbank.ru/favicon.ico",
    mode: "opaque",
  },
];
