import type { ReachabilityTarget } from "@/lib/reachability-targets";

export const WHITELIST_SOURCE_NEWS: { title: string; href: string }[] = [
  {
    title:
      "Важные интернет-сервисы остаются доступными во время ограничений",
    href: "https://digital.gov.ru/news/vazhnye-internet-servisy-ostayutsya-dostupnymi-vo-vremya-ogranichenij",
  },
  {
    title:
      "Список доступных во время ограничений работы мобильного интернета сайтов дополнен (2)",
    href: "https://digital.gov.ru/news/spisok-dostupnyh-vo-vremya-ogranichenij-raboty-mobilnogo-interneta-sajtov-dopolnen-2",
  },
  {
    title:
      "Белый список доступных при ограничениях интернета сайтов вновь расширен",
    href: "https://digital.gov.ru/news/belyj-spisok-dostupnyh-pri-ogranicheniyah-interneta-sajtov-vnov-rasshiren",
  },
];

/**
 * Репрезентативный перечень по публичным сообщениям Минцифры и обзорам СМИ
 * (в перечне ведомства — сотни ресурсов; здесь — ключевые домены для проверки из браузера).
 * Категории для таблицы: госорганы, маркетплейсы, операторы, банки, СМИ, онлайн-сервисы.
 */
export const WHITE_LIST_CATEGORY_ORDER = [
  "Госуслуги и органы власти",
  "Маркетплейсы и объявления",
  "Операторы связи",
  "Банки",
  "СМИ и информация",
  "Онлайн-сервисы",
] as const;

export const WHITE_LIST_REACHABILITY_TARGETS: ReachabilityTarget[] = [
  // —— Госуслуги и органы власти ——
  {
    id: "wl-digital",
    label: "Минцифры",
    region: "Белый список",
    category: "Госуслуги и органы власти",
    host: "digital.gov.ru",
    url: "https://digital.gov.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-gosuslugi",
    label: "Госуслуги",
    region: "Белый список",
    category: "Госуслуги и органы власти",
    host: "gosuslugi.ru",
    url: "https://www.gosuslugi.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-government",
    label: "Правительство РФ",
    region: "Белый список",
    category: "Госуслуги и органы власти",
    host: "government.ru",
    url: "https://www.government.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-kremlin",
    label: "Кремль",
    region: "Белый список",
    category: "Госуслуги и органы власти",
    host: "kremlin.ru",
    url: "https://www.kremlin.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-nalog",
    label: "ФНС России",
    region: "Белый список",
    category: "Госуслуги и органы власти",
    host: "nalog.gov.ru",
    url: "https://www.nalog.gov.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-mvd",
    label: "МВД России",
    region: "Белый список",
    category: "Госуслуги и органы власти",
    host: "mvd.gov.ru",
    url: "https://mvd.gov.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-gosduma",
    label: "Государственная дума",
    region: "Белый список",
    category: "Госуслуги и органы власти",
    host: "duma.gov.ru",
    url: "https://www.duma.gov.ru/favicon.ico",
    mode: "opaque",
  },

  // —— Маркетплейсы и объявления ——
  {
    id: "wl-ozon",
    label: "Ozon",
    region: "Белый список",
    category: "Маркетплейсы и объявления",
    host: "ozon.ru",
    url: "https://www.ozon.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-wb",
    label: "Wildberries",
    region: "Белый список",
    category: "Маркетплейсы и объявления",
    host: "wildberries.ru",
    url: "https://www.wildberries.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-avito",
    label: "Avito",
    region: "Белый список",
    category: "Маркетплейсы и объявления",
    host: "avito.ru",
    url: "https://www.avito.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-yamarket",
    label: "Яндекс Маркет",
    region: "Белый список",
    category: "Маркетплейсы и объявления",
    host: "market.yandex.ru",
    url: "https://market.yandex.ru/favicon.ico",
    mode: "opaque",
  },

  // —— Операторы связи ——
  {
    id: "wl-mts",
    label: "МТС",
    region: "Белый список",
    category: "Операторы связи",
    host: "mts.ru",
    url: "https://mts.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-beeline",
    label: "Билайн",
    region: "Белый список",
    category: "Операторы связи",
    host: "beeline.ru",
    url: "https://beeline.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-megafon",
    label: "МегаФон",
    region: "Белый список",
    category: "Операторы связи",
    host: "megafon.ru",
    url: "https://megafon.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-rostelecom",
    label: "Ростелеком",
    region: "Белый список",
    category: "Операторы связи",
    host: "rt.ru",
    url: "https://rt.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-tele2",
    label: "T2 / Tele2",
    region: "Белый список",
    category: "Операторы связи",
    host: "tele2.ru",
    url: "https://tele2.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-sbermobile",
    label: "СберМобайл",
    region: "Белый список",
    category: "Операторы связи",
    host: "sbermobile.ru",
    url: "https://sbermobile.ru/favicon.ico",
    mode: "opaque",
  },

  // —— Банки ——
  {
    id: "wl-cbr",
    label: "Банк России",
    region: "Белый список",
    category: "Банки",
    host: "cbr.ru",
    url: "https://www.cbr.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-sberbank",
    label: "Сбербанк",
    region: "Белый список",
    category: "Банки",
    host: "sberbank.ru",
    url: "https://www.sberbank.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-vtb",
    label: "ВТБ",
    region: "Белый список",
    category: "Банки",
    host: "vtb.ru",
    url: "https://www.vtb.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-alfa",
    label: "Альфа-Банк",
    region: "Белый список",
    category: "Банки",
    host: "alfabank.ru",
    url: "https://alfabank.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-gpb",
    label: "Газпромбанк",
    region: "Белый список",
    category: "Банки",
    host: "gazprombank.ru",
    url: "https://www.gazprombank.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-tbank",
    label: "Т-Банк",
    region: "Белый список",
    category: "Банки",
    host: "tbank.ru",
    url: "https://www.tbank.ru/favicon.ico",
    mode: "opaque",
  },

  // —— СМИ и информация ——
  {
    id: "wl-ria",
    label: "РИА Новости",
    region: "Белый список",
    category: "СМИ и информация",
    host: "ria.ru",
    url: "https://ria.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-tass",
    label: "ТАСС",
    region: "Белый список",
    category: "СМИ и информация",
    host: "tass.ru",
    url: "https://tass.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-rbc",
    label: "РБК",
    region: "Белый список",
    category: "СМИ и информация",
    host: "rbc.ru",
    url: "https://www.rbc.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-lenta",
    label: "Лента.ру",
    region: "Белый список",
    category: "СМИ и информация",
    host: "lenta.ru",
    url: "https://lenta.ru/favicon.ico",
    mode: "opaque",
  },

  // —— Онлайн-сервисы ——
  {
    id: "wl-yandex",
    label: "Яндекс",
    region: "Белый список",
    category: "Онлайн-сервисы",
    host: "yandex.ru",
    url: "https://yandex.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-rutube",
    label: "RuTube",
    region: "Белый список",
    category: "Онлайн-сервисы",
    host: "rutube.ru",
    url: "https://rutube.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-vk",
    label: "ВКонтакте",
    region: "Белый список",
    category: "Онлайн-сервисы",
    host: "vk.com",
    url: "https://vk.com/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-dzen",
    label: "Дзен",
    region: "Белый список",
    category: "Онлайн-сервисы",
    host: "dzen.ru",
    url: "https://dzen.ru/favicon.ico",
    mode: "opaque",
  },
  {
    id: "wl-nspk",
    label: "НСПК / «Мир»",
    region: "Белый список",
    category: "Онлайн-сервисы",
    host: "nspk.ru",
    url: "https://www.nspk.ru/favicon.ico",
    mode: "opaque",
  },
];
